### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by conky2** [BrandeisClassSearchProject/BrandeisClassSearchIOS#1]
Hi, I was trying to build this project in xCode and I'm getting the following error, as shown in the screenshot.  I have tried renaming the folder (/users/rozoalex/Desktop) and the folder of the project itself from BrandeisClassSearchIOS to BrandeisClassSearchIPHONE -- still no luck.
![screen shot 2017-03-28 at 9 44 58 am](https://cloud.githubusercontent.com/assets/25021281/24408305/3f7738b0-139b-11e7-84f6-c9c99a4323ac.png)

**Comment by rozoalex** [comment]
<img width="349" alt="screen shot 2017-03-29 at 12 02 45 am" src="https://cloud.githubusercontent.com/assets/13334087/24438111/17212286-1413-11e7-8795-d62571673667.png">
<img width="113" alt="screen shot 2017-03-29 at 12 03 38 am" src="https://cloud.githubusercontent.com/assets/13334087/24438128/2f296b72-1413-11e7-9ec1-c81269a942ac.png">
Hi, the problem seems to be that you open the wrong workspace file. Since this project is using libraries managed by Cocoapod, we have to open the xcworkspace instead of xcodeproj. Make sure you have downloaded everything and open the xcworkspace. Then it should be all working. :)

You should see something like the first picture, if you open the xcworkspace.
